"""empty message

Revision ID: b670e18491a7
Revises: 6009ae540dcf
Create Date: 2023-06-15 22:08:17.313285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b670e18491a7'
down_revision = '6009ae540dcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))
        batch_op.alter_column('genre',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.alter_column('genre',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
